# Basic site configuration
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

url: http://matinang.github.io/
baseurl: /
title: Matina Angelopoulou
author: Matina Angelopoulou
description: Personal website
avatar: profile.jpeg
email: matinang@gmail.com
github: matinang
twitter: thematinang
linkedin: matinang
#stackoverflow: username   #e.g: users/2735833/proton1h1
#disqus: username
#google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
